export type ModelCategory = "text" | "image" | "search" | "tts" | "stt" | "local";

export type CatalogModel = {
  providerSlug: string;
  providerName: string;
  apiModelId: string;
  name: string;
  category: ModelCategory;
  inputPricePerMillion: number | null;
  outputPricePerMillion: number | null;
  imagePrice: number | null;
  pricingUnit: "token" | "image" | "character" | "audio_minute" | "local";
  description: string | null;
  source: string;
};

export const MODEL_CATALOG = [
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-5.4-2026-03-05",
    "name": "GPT-5.4",
    "category": "text",
    "inputPricePerMillion": 2.5,
    "outputPricePerMillion": 15,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Dernière génération OpenAI, performances de pointe en raisonnement et créativité.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-5.2-2025-12-11",
    "name": "GPT-5.2",
    "category": "text",
    "inputPricePerMillion": 1.75,
    "outputPricePerMillion": 14,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle avancé avec raisonnement amélioré et large fenêtre de contexte.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-4.1-2025-04-14",
    "name": "GPT-4.1",
    "category": "text",
    "inputPricePerMillion": 2,
    "outputPricePerMillion": 8,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle phare d'OpenAI, excellent en codage et suivi d'instructions complexes.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-5.4-mini-2026-03-17",
    "name": "GPT-5.4 Mini",
    "category": "text",
    "inputPricePerMillion": 0.75,
    "outputPricePerMillion": 4.5,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle mini le plus puissant d'OpenAI, excellent pour codage, usage d'outils et sous-agents.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-5.4-nano-2026-03-17",
    "name": "GPT-5.4 Nano",
    "category": "text",
    "inputPricePerMillion": 0.2,
    "outputPricePerMillion": 1.25,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Version ultra-rapide et économique de GPT-5.4, idéale pour classification, extraction et sous-agents.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "anthropic",
    "providerName": "Claude",
    "apiModelId": "claude-opus-4-7",
    "name": "Claude Opus 4.7",
    "category": "text",
    "inputPricePerMillion": 5,
    "outputPricePerMillion": 25,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle le plus puissant d'Anthropic, excelle en analyse approfondie et tâches complexes.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "anthropic",
    "providerName": "Claude",
    "apiModelId": "claude-opus-4-6",
    "name": "Claude Opus 4.6",
    "category": "text",
    "inputPricePerMillion": 5,
    "outputPricePerMillion": 25,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Version antérieure du modèle le plus puissant d'Anthropic, excelle en analyse approfondie et tâches complexes.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "anthropic",
    "providerName": "Claude",
    "apiModelId": "claude-sonnet-4-5-20250929",
    "name": "Claude Sonnet 4.5",
    "category": "text",
    "inputPricePerMillion": 3,
    "outputPricePerMillion": 15,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Équilibre optimal entre performance et coût, très bon en rédaction et codage.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "anthropic",
    "providerName": "Claude",
    "apiModelId": "claude-haiku-4-5-20251001",
    "name": "Claude Haiku 4.5",
    "category": "text",
    "inputPricePerMillion": 1,
    "outputPricePerMillion": 5,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle rapide et abordable, parfait pour les réponses courtes et le traitement en masse.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-3.1-pro-preview",
    "name": "Gemini 3.1 Pro",
    "category": "text",
    "inputPricePerMillion": 2,
    "outputPricePerMillion": 12,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Dernier modèle Pro de Google, performant en raisonnement multimodal et long contexte.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-3-flash-preview",
    "name": "Gemini 3 Flash",
    "category": "text",
    "inputPricePerMillion": 0.5,
    "outputPricePerMillion": 3,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Dernier modèle FLash, combinant rapidité et une intelligence de pointe.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-3.1-flash-lite-preview",
    "name": "Gemini 3.1 Flash Lite",
    "category": "text",
    "inputPricePerMillion": 0.25,
    "outputPricePerMillion": 1.5,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle ultra-rapide et économique de Google, bon rapport qualité-prix.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemma-4-31b-it",
    "name": "Gemma 4 (31b)",
    "category": "text",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Le modèle dense de Google, conçu pour une qualité maximale à un prix dérisoire. Temporairement gratuit.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "mistral",
    "providerName": "Mistral",
    "apiModelId": "mistral-large-latest",
    "name": "Mistral Large 3",
    "category": "text",
    "inputPricePerMillion": 0.5,
    "outputPricePerMillion": 1.5,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Le modèle phare et le plus performant de Mistral. Cocorico.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "mistral",
    "providerName": "Mistral",
    "apiModelId": "mistral-small-latest",
    "name": "Mistral Small 4",
    "category": "text",
    "inputPricePerMillion": 0.15,
    "outputPricePerMillion": 0.6,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Petit modèle économique, très rapide, avec raisonnement, parfait pour les tâches simples.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "mistral",
    "providerName": "Mistral",
    "apiModelId": "ministral-8b-latest",
    "name": "Ministral 8B",
    "category": "text",
    "inputPricePerMillion": 0.15,
    "outputPricePerMillion": 0.15,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle compact (8B) optimisé pour la rapidité d'exécution et l'edge computing.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "deepseek",
    "providerName": "DeepSeek",
    "apiModelId": "deepseek-chat",
    "name": "DeepSeek V3.2",
    "category": "text",
    "inputPricePerMillion": 0.14,
    "outputPricePerMillion": 0.28,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle phare de DeepSeek, excellent rapport qualité-prix en codage et raisonnement (mode raisonnement activable).",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "grok",
    "providerName": "Grok",
    "apiModelId": "grok-4.20-0309-reasoning",
    "name": "Grok 4.20",
    "category": "text",
    "inputPricePerMillion": 2,
    "outputPricePerMillion": 6,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle phare de xAI, très performant en analyse (mode raisonnement activable).",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "grok",
    "providerName": "Grok",
    "apiModelId": "grok-4-1-fast-reasoning",
    "name": "Grok 4.1 Fast",
    "category": "text",
    "inputPricePerMillion": 0.2,
    "outputPricePerMillion": 0.5,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle rapide et économique de xAI, fenêtre de contexte de 2M tokens.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "zai",
    "providerName": "Z.ai",
    "apiModelId": "glm-5.1",
    "name": "GLM-5.1",
    "category": "text",
    "inputPricePerMillion": 1.4,
    "outputPricePerMillion": 4.4,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle codage le plus puissant de Zhipu AI, 200K de contexte, avec mode raisonnement activable.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "zai",
    "providerName": "Z.ai",
    "apiModelId": "glm-5",
    "name": "GLM-5",
    "category": "text",
    "inputPricePerMillion": 1,
    "outputPricePerMillion": 3.2,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle phare de Zhipu AI (744B MoE), rival des meilleurs modèles mondiaux (mode raisonnement activable).",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "zai",
    "providerName": "Z.ai",
    "apiModelId": "glm-4.7-flash",
    "name": "GLM-4.7 Flash",
    "category": "text",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Modèle ultra-rapide de Zhipu, gratuit, bon pour les tâches simples.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-3-pro-image-preview",
    "name": "Nano Banana Pro",
    "category": "image",
    "inputPricePerMillion": 2,
    "outputPricePerMillion": 12,
    "imagePrice": 0.134,
    "pricingUnit": "image",
    "description": "Génération d'images via Gemini Pro, haute qualité et bonne compréhension des prompts.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-3.1-flash-image-preview",
    "name": "Nano Banana 2",
    "category": "image",
    "inputPricePerMillion": 0.5,
    "outputPricePerMillion": 3,
    "imagePrice": 0.067,
    "pricingUnit": "image",
    "description": "Génération d'images rapide et économique basée sur Gemini Flash.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-image-1.5",
    "name": "GPT Image 1.5",
    "category": "image",
    "inputPricePerMillion": 5,
    "outputPricePerMillion": 10,
    "imagePrice": 0.133,
    "pricingUnit": "image",
    "description": "Modèle de génération d'images d'OpenAI, excellent en réalisme et créativité.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-image-1-mini",
    "name": "GPT Image 1 Mini",
    "category": "image",
    "inputPricePerMillion": 2,
    "outputPricePerMillion": 0,
    "imagePrice": 0.036,
    "pricingUnit": "image",
    "description": "Version mini de GPT Image, nettement moins chère, idéale pour les itérations rapides.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openrouter",
    "providerName": "OpenRouter",
    "apiModelId": "black-forest-labs/flux.2-klein-4b",
    "name": "Flux 2 Klein 4B",
    "category": "image",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": 0.01,
    "pricingUnit": "image",
    "description": "Modèle Flux rapide et économique, idéal pour le prototypage et les itérations.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openrouter",
    "providerName": "OpenRouter",
    "apiModelId": "black-forest-labs/flux.2-pro",
    "name": "Flux 2 Pro",
    "category": "image",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": 0.03,
    "pricingUnit": "image",
    "description": "Modèle Flux professionnel avec textures nettes et éclairage stable.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openrouter",
    "providerName": "OpenRouter",
    "apiModelId": "black-forest-labs/flux.2-flex",
    "name": "Flux 2 Flex",
    "category": "image",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": 0.06,
    "pricingUnit": "image",
    "description": "Modèle Flux polyvalent, excellent en typographie et édition multi-référence.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openrouter",
    "providerName": "OpenRouter",
    "apiModelId": "black-forest-labs/flux.2-max",
    "name": "Flux 2 Max",
    "category": "image",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": 0.07,
    "pricingUnit": "image",
    "description": "Modèle Flux haut de gamme, qualité maximale et meilleure compréhension des prompts.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "perplexity",
    "providerName": "Perplexity",
    "apiModelId": "sonar",
    "name": "Sonar",
    "category": "search",
    "inputPricePerMillion": 1,
    "outputPricePerMillion": 1,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Recherche web avec synthèse de sources multiples et citations. 5$/1k recherches web",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "perplexity",
    "providerName": "Perplexity",
    "apiModelId": "sonar-pro",
    "name": "Sonar Pro",
    "category": "search",
    "inputPricePerMillion": 3,
    "outputPricePerMillion": 15,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Recherche web avancée avec synthèse de sources multiples et citations. 5$/1k recherches web",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "perplexity",
    "providerName": "Perplexity",
    "apiModelId": "sonar-reasoning-pro",
    "name": "Sonar Reasoning Pro",
    "category": "search",
    "inputPricePerMillion": 2,
    "outputPricePerMillion": 8,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "⚠️ Très coûteux. Recherche web avec raisonnement approfondi pour les questions complexes. 5$/1k recherches web",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "gpt-4o-mini-tts",
    "name": "OpenAI (gpt-4o-mini-tts)",
    "category": "tts",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "character",
    "description": "Synthèse vocale rapide et expressive d'OpenAI.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-3.1-flash-tts-preview",
    "name": "Google (Gemini 3.1 Flash TTS)",
    "category": "tts",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Dernière génération TTS de Google — 70+ langues, dialogue multi-voix, contrôle expressif via tags audio.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-2.5-flash-preview-tts",
    "name": "Google (Gemini 2.5 Flash TTS)",
    "category": "tts",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Synthèse vocale de Google via Gemini, voix naturelles multilingues.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "mistral",
    "providerName": "Mistral",
    "apiModelId": "voxtral-mini-tts-2603",
    "name": "Mistral (Voxtral Mini TTS)",
    "category": "tts",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "character",
    "description": "Synthèse vocale légère et rapide par Mistral.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "system",
    "providerName": "System",
    "apiModelId": "system-tts",
    "name": "Système (navigateur)",
    "category": "tts",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Synthèse vocale native du navigateur (voix du système).",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "openai",
    "providerName": "OpenAI",
    "apiModelId": "whisper-1",
    "name": "OpenAI (Whisper)",
    "category": "stt",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "audio_minute",
    "description": "Transcription audio précise et multilingue par OpenAI.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "google",
    "providerName": "Gemini",
    "apiModelId": "gemini-3.1-flash-lite-preview",
    "name": "Google (Gemini 3.1 Flash Lite)",
    "category": "stt",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "token",
    "description": "Transcription audio via Gemini Flash Lite, rapide et polyvalent.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "mistral",
    "providerName": "Mistral",
    "apiModelId": "voxtral-mini-latest",
    "name": "Mistral (Voxtral Mini 2)",
    "category": "stt",
    "inputPricePerMillion": null,
    "outputPricePerMillion": null,
    "imagePrice": null,
    "pricingUnit": "audio_minute",
    "description": "Modèle de transcription de pointe par Mistral, léger et rapide.",
    "source": "kiro_v3_usb_2026-05-09"
  },
  {
    "providerSlug": "local",
    "providerName": "Ollama / Lenovo local",
    "apiModelId": "llama3.1-local",
    "name": "llama3.1 local",
    "category": "local",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": null,
    "pricingUnit": "local",
    "description": "Modèle local Ollama sur Lenovo, coût API nul.",
    "source": "torquepilot"
  },
  {
    "providerSlug": "local",
    "providerName": "Ollama / Lenovo local",
    "apiModelId": "qwen-local",
    "name": "qwen local",
    "category": "local",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": null,
    "pricingUnit": "local",
    "description": "Modèle local Qwen via Ollama/Lenovo.",
    "source": "torquepilot"
  },
  {
    "providerSlug": "local",
    "providerName": "Ollama / Lenovo local",
    "apiModelId": "mistral-local",
    "name": "mistral local",
    "category": "local",
    "inputPricePerMillion": 0,
    "outputPricePerMillion": 0,
    "imagePrice": null,
    "pricingUnit": "local",
    "description": "Modèle local Mistral via Ollama/Lenovo.",
    "source": "torquepilot"
  }
] as const satisfies readonly CatalogModel[];
